### PR TITLE
Add an "on_failure" hook function

### PR DESCRIPTION
**Pull request by matthijskooijman**
This function can be used to run custom code on failure (e.g. to print some variable values at the time of the failure, such as [here](https://github.com/3devo/AtTinyBootloader/blob/94df47846863f0a6d5bf164bcf2b8a9f79eff315/BootloaderTest/BootloaderTest.ino#L363-L372)), or it can be used to let helper functions (that use the assert macros) return a value (e.g. [here](https://github.com/3devo/AtTinyBootloader/blob/94df47846863f0a6d5bf164bcf2b8a9f79eff315/BootloaderTest/BootloaderTest.ino#L130-L136) and [here](https://github.com/3devo/AtTinyBootloader/blob/94df47846863f0a6d5bf164bcf2b8a9f79eff315/BootloaderTest/BootloaderTest.ino#L183)).

This PR contains the commits from #64 too, since it touches the same lines and is built on top of those commits.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
If I missed some feature that allows using helper functions in the way suggested here with the current arduinounit codebase, please also let me know :-)

**Comment by wmacevoy** [comment]
I need a  C++ lesson.  Your def declared on_failure to return void, and the assert returns on_failure().  I did not think that was legal (tho I think it should be in the proper context).

**Comment by matthijskooijman** [comment]
It's a bit counter-intuitive, but it allows replacing `on_failure` by something that does not return void, and then return that instead. I suspect this might have been added to facilitate C++ templates, though it might be valid in C as well, dunno.

**Comment by wmacevoy** [comment]
Ok there is a version of this which (#iss73) I hope does what you want.  You can now add optional messages to asserts.  You can also create any optional function call by digging a little deeper, but I think the macros take care of almost everyone's needs.  If you really need just an optional function, you can use the lambda notation with the macros ASSERT_EQ_3, etc:

```
assertEqual(x,y,"case k="<<k); // extra message when output
```
```
assertOpMsg(x,compareMoreOrEqual,">=",y,[&]()->{ your_code_here; });
```
`MoreOrEqual` can also be `Equal`, `NotEqual`, `Less`, `More`, `LessOrEqual`

An important difference is the method is called when the message is printed (usually this is when the assert fails, but this can be all the time with the proper level of verbosity).  You cannot assume the test passed or failed, just that output was requested.

**Comment by matthijskooijman** [comment]
Woah, impressive work. It took me a while to collect all relevant changes from all related commits, but I think I see what you're doing now. As for the implementation:
 - The new macros needed to get an optional macro argument are clever, but also messy.
 - Very nice that you can use the `<<` operator in the `msg` argument to add data, that makes things look really clean.

However, I believe this feature only handles one half of my original problem: It allows printing extra data about a testcase in a nice way. However, it does not allow the second case: letting helper functions return `false` when a testcase fails, so callers of the helper function know when to abort the entire testcase.

E.g. see [this example](https://github.com/3devo/AtTinyBootloader/blob/94df47846863f0a6d5bf164bcf2b8a9f79eff315/BootloaderTest/BootloaderTest.ino#L183) where [`run_transaction_ok()`](https://github.com/3devo/AtTinyBootloader/blob/94df47846863f0a6d5bf164bcf2b8a9f79eff315/BootloaderTest/BootloaderTest.ino#L130-L136) is a helper function that (with my original changes) returns false when an assert fails.

Thinking about this now, I guess this could be solved by checking the current test status instead. E.g. instead of my current code:

    assertTrue(run_transaction_ok(Commands::GET_PROTOCOL_VERSION, nullptr, 0, data, sizeof(data)));

You would get two lines:

    run_transaction_ok(Commands::GET_PROTOCOL_VERSION, nullptr, 0, data, sizeof(data)
    assertTrue(Test::current->state != Test::DONE_FAIL)

Where the latter could probably be wrapped inside a `AssertNotFailed()` or something.

**Comment by wmacevoy** [comment]
There have been a lot of changes.  I am concerned about the support of the __weak__ attribute (en vitro tests in LLVM).  If you are happy with some assertCurrentTestPass/checkCurrentTestPass etc macros that seems portable and works for you, there is a version of this in branch pr65; can you look at it?  I think your example translates to
```
run_transaction_ok(Commands::GET_PROTOCOL_VERSION, nullptr, 0, data, sizeof(data));
assertCurrentTestNotFail();
```
or, perhaps better,
```
run_transaction_ok(Commands::GET_PROTOCOL_VERSION, nullptr, 0, data, sizeof(data));
if (checkCurrentTestDone()) return; // resolved
```

**Comment by wmacevoy** [comment]
Well, variadic macros with no arguments are not supported on esp8266, which is something that feels important to support.  This means the asserts will not compile on that board.  Now I'm stuck.

**Comment by matthijskooijman** [comment]
Looking at the branch, that looks good to me. I'll try to rewrite my testcases to use this new code, and see if that works properly. I'm not yet sure when I'll find time for that, though (maybe tomorrow, maybe in a few weeks).

I'm not sure what you meant with your concern about the `weak` attribute?

As for empty variadic macros on ESP, any idea why that's broken? Does the ESP core use a different compiler than gcc, or an older version or something? Or could it be a matter of some compile flag?

**Comment by wmacevoy** [comment]
I am ok with this being a bug in ESP8266 (works on ESP32).  I don't think it is used much and there is an easy work-around.  This might be a way to submit an issue with them.  I'll leave this until you modify your tests and see if they are ok.  --- are you willing to become a collaborator on the ArduinoUnit project?  It could really use your help.

**Comment by wmacevoy** [comment]
... I merged the typeof bit as a separate pr64 branch...

**Comment by matthijskooijman** [comment]
> I'll leave this until you modify your tests and see if they are ok.

Ok, I'll try to do this soon then.

> are you willing to become a collaborator on the ArduinoUnit project? It could really use your help.

I'm afraid I can't dedicate the time, I'm already maintaining enough projects as it is...

**Comment by wmacevoy** [comment]
Had to ask and I understand about the maintenance --- thanks for helping the project get better

**Comment by matthijskooijman** [comment]
Two more thoughts: After some macro processing, the `assertOpMsg` macro actually takes a *callable* (e.g. a lambda) instead of just a message to print. If that could be exposed, you could do something like:

   test(100_command_not_supported) {
     uint8_t cmd = Commands::END_OF_COMMANDS;
     auto on_message = [&cmd](bool) { Serial.print("cmd: "); Serial.println(cmd); };
     while (cmd != 0) {
       uint8_t status;
       run_transaction(cmd, nullptr, 0, &status);
       assertCurrentTestNotFail(on_message);
       assertEqual(status, Status::COMMAND_NOT_SUPPORTED, on_message);
       ++cmd;
     }
   }

This is essentially similar to my previous `on_failure` hook, except that it is passed explicitly. Allowing this would fix all problems described in the previous comment, since the printing is again in a dedicated function, so it can do printing in a loop, do hex printing or whatever is required. And when multiple asserts are involved, you only need to duplicate the reference to the `on_message` function, not the entire message.

Above, I just passed `on_message` explicitly, which would mean losing support for passing a message directly. That would of course be a waste, since for simple messages, passing the message directly is nice and concise. However, supporting both of these at the same time seems impossible, since the direct message needs some preprocessor magic, so we can't rely on C++ type overloading or template specialization here...

One way would be to slightly complicate the "direct message" case, by doing something like:

  #define ADD_INFO(message) [&](bool ok)->void { (void)ok; Test::Printer() << ARDUINO_UNIT_STRING(" [") << message << ARDUINO_UNIT_STRING("]");
  assertCurrentTestNotFail(ADD_INFO("foo" << 123));

**Comment by wmacevoy** [comment]
Ok, there is a (I think) solution for this.  As of `v2.8-alpha`,  asserts now have two optional arguments.  One is for the message, and the second is for an optional return value (so asserts can work in functions that return a value).  This last can be hijacked pretty easily with an infrequently used C notation `(a,b,c)` as an expression evaluates a b and c and then has a value of the last term, c, so
```c++
void on_fail() { .. }
```
and later
```c++
assertRelation(on,"message",on_fail())
```
Or, if you want to return a non-void value:
```c++
assertRelation(on,"message",(on_fail(), retval));
```

**Comment by matthijskooijman** [comment]
Looks good, and seems to compile as well. I did run into some other reset problem on my board, so haven't been able to test this completely yet. When I do (will be next week), I'll let you know how this goes. Thanks!

**Comment by matthijskooijman** [comment]
W00ps, forgot to comment here. I tested this a while ago, works like a charm, thanks! Now only the multiple-run thing in another PR keeps me from using an unmodified copy of arduinounit :-)

**Pull request closed without merging**
