### PR TITLE
replace typeof with __typeof__

### PR DESCRIPTION
**Pull request by apieum**
Fix bug for some compiler see: https://gcc.gnu.org/onlinedocs/gcc/Typeof.html

### CODE REVIEW

**Comment by wmacevoy** [comment]
I don't think we should merge this change. This is a gcc-compiler specific change for C compatibility, but this is a very c++ library.  Addressing a hypothetical c compatibility vs hypothetical portability seems like wash.  Does someone have an example environment where this matters?

**Comment by apieum** [comment]
As you wish, I've suggested this because I was trying to launch my tests on ncore.
Finaly, it was not the only problem and I had to rewrite a big part of arduinounit to be able to launch it on ncore and arduino.
code here: https://github.com/apieum/ncore/tree/serialprint/extras/arduinounit

**Comment by wmacevoy** [comment]
Ok, that's different; without context I couldn't tell what problem it
solved.

I'm on my phone, so it's not great for looking at code; but are you saying
yours works on arduino and ncore?  There are a number of funny
implementation choices because of odd parts of versions of the arduino
hardware and software?  What have you tested about compatibility of your
version?

Warren MacEvoy
wmacevoy@coloradomesa.edu
http://www.coloradomesa.edu/~wmacevoy
970-248-1070


On May 23, 2015, at 7:28 AM, Grégory Salvan <notifications@github.com>
wrote:

As you wish, I've suggested this because I was trying to launch my tests on
ncore.
Finaly, it was not the only problem and I had to rewrite a big part of
arduinounit to be able to launch it on ncore and arduino.
code here:
https://github.com/apieum/ncore/tree/serialprint/extras/arduinounit

—
Reply to this email directly or view it on GitHub
<https://github.com/mmurdoch/arduinounit/pull/41#issuecomment-104902250>.

**Comment by wmacevoy** [comment]
I looked over the code and saw you replaced the wildcard matching with
posix expressions; I'm not comfortable with the resources that would take
generally on the smaller chips; which is why I wrote the other version.

Warren MacEvoy
wmacevoy@coloradomesa.edu
http://www.coloradomesa.edu/~wmacevoy
970-248-1070


On May 23, 2015, at 7:28 AM, Grégory Salvan <notifications@github.com>
wrote:

As you wish, I've suggested this because I was trying to launch my tests on
ncore.
Finaly, it was not the only problem and I had to rewrite a big part of
arduinounit to be able to launch it on ncore and arduino.
code here:
https://github.com/apieum/ncore/tree/serialprint/extras/arduinounit

—
Reply to this email directly or view it on GitHub
<https://github.com/mmurdoch/arduinounit/pull/41#issuecomment-104902250>.

**Comment by apieum** [comment]
Yes, it's because I use this version to compile with ncore and the original
version to compile on arduino.
But I realized that most of problems I had was because ncore version of
arduino lib was old, and I'm now trying to update ncore arduino lib. (ex.
Printable not exists...)

Otherwise for typeof, maybe a solution is to have a macro like:
```
#ifdef __GNUC__
  #define typeof __typeof__
#endif
```

What do you think about that ?


2015-05-24 21:26 GMT+02:00 Warren MacEvoy <notifications@github.com>:

**Comment by wmacevoy** [comment]
You understand the regex and wildcard matches are different; so

Willard: a* anything staring with an a
Regex: a* zero or more a's

This is a surprising difference to users of the api

I don't see the typeof need: you are using classes, then you are using the
gnu c++ compiler which is fine without all the _'s.  No?

Warren MacEvoy
wmacevoy@coloradomesa.edu
http://www.coloradomesa.edu/~wmacevoy
970-248-1070


On May 25, 2015, at 1:38 AM, Grégory Salvan <notifications@github.com>
wrote:

Yes, it's because I use this version to compile with ncore and the original
version to compile on arduino.
But I realized that most of problems I had was because ncore version of
arduino lib was old, and I'm now trying to update ncore arduino lib. (ex.
Printable not exists...)

Otherwise for typeof, maybe a solution is to have a macro like:
```
#ifdef __GNUC__
#define typeof __typeof__
#endif
```

What do you think about that ?


2015-05-24 21:26 GMT+02:00 Warren MacEvoy <notifications@github.com>:

> I looked over the code and saw you replaced the wildcard matching with
> posix expressions; I'm not comfortable with the resources that would take
> generally on the smaller chips; which is why I wrote the other version.
>
>
> Warren MacEvoy
> wmacevoy@coloradomesa.edu
> http://www.coloradomesa.edu/~wmacevoy
> 970-248-1070
>
>
> On May 23, 2015, at 7:28 AM, Grégory Salvan <notifications@github.com>
> wrote:
>
> As you wish, I've suggested this because I was trying to launch my tests
on
> ncore.
> Finaly, it was not the only problem and I had to rewrite a big part of
> arduinounit to be able to launch it on ncore and arduino.
> code here:
> https://github.com/apieum/ncore/tree/serialprint/extras/arduinounit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmurdoch/arduinounit/pull/41#issuecomment-104902250>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmurdoch/arduinounit/pull/41#issuecomment-105055536>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/mmurdoch/arduinounit/pull/41#issuecomment-105154372>.

**Comment by apieum** [comment]
You're right for wildcard, I haven't thought about it (no needs for
include, exclude), I had to do it fast and now seeing I can do real TDD
with arduino I'm thinking about improving it and sharing.

"typeof" generate build error with c++, I had to replace with "__typeof__"
to compile for x86_64, avr-gcc works well with "typeof".

Error message (truncated):
```
In file included from /home/gregory/workspace/four/tests/testThermo.ino:1:0:
/home/gregory/workspace/four/tests/testThermo.ino: In member function
‘virtual void
test_Thermocouple_TypeE_returns_coefs0_when_temp_is_lower_than_minus_100::once()’:
/home/gregory/workspace/ncore/src/extras/arduinounit/ArduinoUnit.h:172:72:
erreur: ‘typeof’ was not declared in this scope
 #define assertOp(arg1,op,op_name,arg2) if
(!Test::assertion<typeof(arg2)>(__FILE__,__LINE__,#arg1,(arg1),op_name,op,#arg2,(arg2)))
return;
```
... lot of messages ...

```
c++ -c -o ./../build/tests/testThermo.o -fprofile-arcs -ftest-coverage -g
-O0 -fno-inline -Wall -Wextra
-I/home/gregory/workspace/ncore/src/extras/arduinounit -std=c++0x -O
-DNATIVE=1 -DARDUINO=100 -I/home/gregory/workspace/four
-I/home/gregory/workspace/ncore/src
-I/home/gregory/workspace/ncore/src/internal
-I/home/gregory/workspace/four/src ./../build/tests/testThermo.cpp

...failed C++ ./../build/tests/testThermo.o ...
...skipped four for lack of testThermo.o...
...failed updating 1 target(s)...
...skipped 1 target(s)...
...updated 28 target(s)...
```

Maybe I wasn't clear about what I'm doing.
For TDD I need rapid feedback so I compile tests on my pc (gentoo arch
x86_64) with ncore and have tests results directly in a shell (with jam
each update < 1s).
Then for continuous integration I want to deploy tests suites on an arduino
board. I have modified ino to manage src and build dirs (added upload-tests
and build-tests commands)

So I took arduinounit, include it in ncore and have started to modify build
blocking parts.
I build for avr with original arduinounit (in project folder ./lib) and for
x86_64 with modified one (same api).

Now It's alright for me, everything is ok in my toolchain for my usage, but
it may be interesting to share it, don't you think ?
I'm just suggesting a change I think blocking, in order to have, maybe a
day, arduinounit building to other targets than avr.

I'm not confident with C++, so I don't know what's the best solution for
it, just the one which function. :)

**Comment by wmacevoy** [comment]
__typeof__ is old g++, while newer c++ compilers (g++ included) support typeof; I think in the end this is something that will have to be a #define in a config file for the ncore target; probably setup via a config script that tries to build __typeof__ and typeof code and decides which works on the target.  Most of the world, including arduino, uses typeof.  I don't think this should be addressed in ArduinoUnit, but a "config.h" that your build has.  The regex changes are too overhead unknown and overkill (most people do little or no filtering on tests IMHO).

As far as the TDD, if the target supports a large code space, then uploading all tests and using filtering can create fast testing environments  (the arduinounit self tests are like this, where the test filtering patterns are controlled via serial port data).  

If you don't, then you have to upload multiple firmwares (which is slow on many devices) using blocking tests.  You might want to look at the discussion

https://github.com/mmurdoch/arduinounit/issues/30

About a framework for doing this.

**Comment by apieum** [comment]
typeof is only supported by gnu standard which means you have to specify
-std=gnu++11 to compile it (or specify nothing if default mode is gnu),
it's not a question of compiler version (I run GCC 4.8.4), I've just
replaced -std=c++"something" and can compile it.

For regexp I agree it's not a good idea to change this behaviour, the
reason I have replaced it in arduinounit is because Printable and
__flashstringhelper were not supported, but this is probably a ncore
problem due to old arduino lib emulation, that's why I've not suggested
this change.


thank you for replies.

2015-05-26 2:46 GMT+02:00 Warren MacEvoy <notifications@github.com>:

**Comment by apieum** [comment]
2015-05-26 2:46 GMT+02:00 Warren MacEvoy <notifications@github.com>:

>  As far as the TDD, if the target supports a large code space, then
> uploading all tests and using filtering can create fast testing
> environments (the arduinounit self tests are like this, where the test
> filtering patterns are controlled via serial port data).
>
> If you don't, then you have to upload multiple firmwares (which is slow on
> many devices) using blocking tests. You might want to look at the discussion
>
> #30 <https://github.com/mmurdoch/arduinounit/issues/30>
>
> About a framework for doing this.
>

* far from unit testing

but "the test is more important than the unit" (great master Flying
Feathers, the way of testivus
<http://www.agitar.com/downloads/TheWayOfTestivus.pdf>) ;-D

**Pull request closed without merging**
